### ISSUE TITLE
EchoSVG on Android

### ISSUE THREAD

**Issue by tomveich** [css4j/echosvg#85] opened 2023-08-08 20:11 UTC
I opened a new issue for this. If I try to convert any (valid) SVG, I keep getting this error.
```
FATAL EXCEPTION: main
          Process: com.myapp, PID: 14681
          java.lang.ClassCastException: io.sf.carte.echosvg.dom.GenericElement cannot be cast to org.w3c.dom.svg.SVGSVGElement
           at io.sf.carte.echosvg.anim.dom.SVGOMDocument.getRootElement(SVGOMDocument.java:223)
           at io.sf.carte.echosvg.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:228)
           at io.sf.carte.echosvg.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:97)
           at io.sf.carte.echosvg.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:93)
           at io.sf.carte.echosvg.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:199)
           ...
```
The compiler suggests it's being caused by the return statement in `SVGSVGElement getRootElement()`:
```
public SVGSVGElement getRootElement() {
return (SVGSVGElement) getDocumentElement();
}
```
File:
`echosvg/echosvg-anim/src/main/java/io/sf/carte/echosvg/anim/dom/SVGOMDocument.java`

Let me know if you need any specific details
Thank you

**Comment by carlosame** [comment] 2023-08-09 07:08
> If I try to convert any (valid) SVG, I keep getting this error.

This implies that your XML parser is not doing namespace handling, so my suggestion would be:

```java
SAXParserFactory factory = SAXParserFactory.newInstance();
factory.setNamespaceAware(true);
SAXParser parser = factory.newSAXParser();
XMLReader reader = parser.getXMLReader();
transcoderInput.setXMLReader(reader);
```
or alternatively:
```java
SAXParser parser = SAXParserFactory.newSAXParser() 
XMLReader reader = parser.getXMLReader();
reader.setFeature("http://xml.org/sax/features/namespaces", true);
transcoderInput.setXMLReader(reader);
```
or whatever Android requires to set in order to support namespaces. It is weird, because `http://xml.org/sax/features/namespaces` is supposed to be `true` by default. Please let me know what works so I can put it in the FAQ.

That said, I would not expect EchoSVG to work on Android because that OS does not have the `java.awt` package(s). I know that there is a Harmony-based open source replacement but I would be surprised if it is complete enough. Again, if you manage to run it on Android please let me know so I can put that on the FAQ.

**Comment by tomveich** [comment] 2023-08-09 08:46
None of the code you suggested affected the output. The error persists.
I found this library in the official android docs: `https://developer.android.com/reference/org/xmlpull/v1/package-summary` but I couldn't find a reader() method there.
Thank you

**Comment by carlosame** [comment] 2023-08-09 09:15
> None of the code you suggested affected the output. The error persists.

Then I'd suggest debugging what happens inside [`SAXDocumentFactory.startElement`](https://github.com/css4j/echosvg/blob/a20a2c26bb9d87e7ea14608affc454e44e7223ba/echosvg-dom/src/main/java/io/sf/carte/echosvg/dom/util/SAXDocumentFactory.java#L705) when it is processing the `svg` element. I mean checking which `uri` is it reporting when the `localName` is `svg`. If `uri` is `null` as I say (because it's the only way I can reproduce your issue) then the XML parser is to blame, not EchoSVG.

> I found this library in the official android docs: `https://developer.android.com/reference/org/xmlpull/v1/package-summary` but I couldn't find a reader() method there. Thank you

The XmlPullParser does not use SAX and is therefore incompatible with EchoSVG's DOM, although [`SAXDocumentFactory`](https://github.com/css4j/echosvg/blob/master/echosvg-dom/src/main/java/io/sf/carte/echosvg/dom/util/SAXDocumentFactory.java) could be modified to use it. If you are willing to provide a Pull Request providing that functionality, I could merge it. The XMLPull API is explained here:

https://www.xmlpull.org/v1/download/unpacked/doc/quick_intro.html

**Comment by tomveich** [comment] 2023-08-16 19:55
As much as I'd like to, I'm afraid I'm not experienced enough to provide such a PR. For my purpose, I am left to convert the images on backend.

**Comment by carlosame** [comment] 2023-08-16 21:07
> As much as I'd like to, I'm afraid I'm not experienced enough to provide such a PR.

It is not too complicated once one understands the XmlPull API, but definitely a large amount of work. I don't think it would be worth the result (and a lot of people dislikes the XmlPull parser because it silently removes XML entities).

> For my purpose, I am left to convert the images on backend.

There must be a way to get the namespaces with the SAX parser on Android, however even if you managed to solve that you'd probably get stuck on the AWT stuff: https://github.com/css4j/echosvg/wiki/FAQ#does-it-run-on-android

I'm closing this as not planned, feel free to reopen if you make any progress.

**Closed by carlosame** 2023-08-16 21:07 UTC

**Comment by carlosame** [comment] 2023-08-18 11:19
Incidentally, [css4j-dom4j](https://github.com/dom4j/dom4j) does support the XmlPull parser, see the [`XPP3Test`](https://github.com/css4j/css4j-dom4j/blob/master/junit/io/sf/carte/doc/dom4j/XPP3Test.java) for an example:

https://github.com/css4j/css4j-dom4j/blob/48f903a9509e0884fc1574e2457684d02aa69a59/junit/io/sf/carte/doc/dom4j/XPP3Test.java#L30-L35

So if you load the file with css4j-dom4j and then provide the DOM document to `TranscoderInput`, that may work:

```java
XHTMLDocumentFactory factory = XHTMLDocumentFactory.getInstance();
XPP3Reader reader = new XPP3Reader(factory);
Reader re = new FileReader(svgFile, "utf-8");
XHTMLDocument document = (XHTMLDocument) reader.read(re);
re.close();

TranscoderInput transcoderInput = new TranscoderInput(document);
PNGTranscoder pngTranscoder = PNGTranscoder()
pngTranscoder.transcode(transcoderInput, transcoderOutput);
```

And once EchoSVG 0.3.3 is released, you should be able to benefit from the support for namespaceless HTML documents. The idea would be to load the SVG file into a DOM document (from EchoSVG DOM, css4j's DOM or any other DOM, it does not matter), then create an `html` element, append the document root to it, then append the `html` element to the document (or just replace the nodes) and provide it to the `TranscoderInput`:

```java
DocumentFactory df = new SAXDocumentFactory(GenericDOMImplementation.getDOMImplementation());
String uri = svgFile.toURI().toString();
Reader re = new FileReader(svgFile, "utf-8");
Document document = df.createDocument(null, "svg", uri, re);
re.close();

Element html = document.createElement("html");
Element svg = document.getDocumentElement();
document.replaceChild(html, svg);
html.appendChild(svg);
// If the document has a DOCTYPE you'll have to remove it

TranscoderInput transcoderInput = new TranscoderInput(document);
PNGTranscoder pngTranscoder = PNGTranscoder()
pngTranscoder.transcode(transcoderInput, transcoderOutput);
```
Haven't tested but should work.
